# Generated by Django 5.2.3 on 2025-06-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='forgot_password_otp',
            field=models.IntegerField(default=654321),
        ),
    ]
