# Generated by Django 5.2.3 on 2025-06-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_users_forgot_password_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
