# Generated by Django 5.2.3 on 2025-06-25 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_logoutdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserSalary',
            fields=[
                ('salary', models.PositiveIntegerField(default=0)),
                ('reset_day', models.PositiveSmallIntegerField(default=1)),
                ('fixed_expenses', models.JSONField(default=dict)),
                ('saving', models.PositiveIntegerField(default=0)),
                ('emergency_percent', models.PositiveSmallIntegerField(default=10)),
                ('personal_percent', models.PositiveSmallIntegerField(default=40)),
                ('remaining_salary', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expense.users')),
                ('UID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
