# Generated by Django 5.2.3 on 2025-06-25 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_rename_user_id_userdetails_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersalary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.users'),
        ),
    ]
