# Generated by Django 5.2.3 on 2025-06-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0011_alter_member_member_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
